name = "botgroup-chat"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-13"

[[kv_namespaces]]
binding = "bgkv"
id = "6b592babb2834c52a6505936349e96ea"

[[d1_databases]]
binding = "bgdb"
database_name = "friends"
database_id = "26707859-b1b6-4254-b7a0-18de672f96f8"

[vars]
GITHUB_CLIENT_ID = "0v231i0QzY0SaCX2KZ0c"
GITHUB_CLIENT_SECRET = "efd780a82f48ffb9bcd3d4eec7e190a84550f940"
JWT_SECRET = "mysecret123456"
NEXTAUTH_URL = "https://botgroup-chat-4bu.pages.dev"
OPENAI_API_KEY = "sk-of-1SkwKWuRYQQsHEUcDcGcItsfoigcCmQOdkCCUHSCaHIWEZaPCoXsdnDnpf1CAIrAe"
OPENAI_BASE_URL = "https://api.ofox.ai/v1"
